version: "2" # version matters, see https://docs.docker.com/compose/networking/
networks: 
  back: 
  front: 
services: 
  laraveldatabase: 
    restart: always
    image: mysql:5.7
    volumes: # mount custom config at runtime 
      - ./mysqldata:/docker-entrypoint-initdb.d
    ports:
     - 33306:3306
    environment: 
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "twinlist"
       MYSQL_USER: "ubuntu"
       MYSQL_PASSWORD: "ubuntu"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "true" 
    networks: 
      back:  
        aliases: 
        - dbserver  
  laravelweb: 
    restart: always
    #image: php:7.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    #user: www-data
    volumes: # mount custom config at runtime 
      - ./laravel:/var/www/html 
    networks: 
     - back
     - front 
    ports: 
      - 90:80
      - 4443:443
  laravelphpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: "laraveldatabase"
    networks: 
     - back
    ports: 
      - 9090:80  
  node:
    image: "node:8-alpine"
    #restart: always
    # user: "node"
    working_dir: /home/node/app
    # environment:
    #    - NODE_ENV=production
    volumes:
      - ./laravel:/home/node/app
    networks: 
     - back
    #command: "npm install"
    # command: "npm run development"
    #command: "npm install react-router-dom react-redux react-datepicker redux redux-thunk"

    command: "npm run watch -- --watch-poll"     
